models/User.php
<?php

namespace app\models;

use Yii;
use yii\base\NotSupportedException;
use yii\db\ActiveRecord;
use yii\helpers\Security;
use yii\web\IdentityInterface;
/**
 * This is the model class for table "tbl_user".
 *
 * @property string $userid
 * @property string $username
 * @property string $password
 */
class User extends \yii\db\ActiveRecord  implements IdentityInterface
{
	const ROLE_USER = 'User';
    const ROLE_MODERATOR = 'Moderator';
    const ROLE_ADMIN = 'Admin';
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'user';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['username', 'password'], 'required'],
            [['username', 'password', 'fullname'], 'string', 'max' => 100]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'userid'   => 'Userid',
            'username' => 'שם משתמש',
            'password' => 'סיסמה',
			'fullname' => 'שם מלא',
			'email' => 'כתובת מייל',
			'security_question' => 'סיסמה',
			'status' => 'סוג הרשאה'
        ];
    }
    /** INCLUDE USER LOGIN VALIDATION FUNCTIONS**/
        /**
     * @inheritdoc
     */
    public static function findIdentity($id)
    {
        return static::findOne($id);
    }

    /**
     * @inheritdoc
     */
/* modified */
    public static function findIdentityByAccessToken($token, $type = null)
    {
          return static::findOne(['access_token' => $token]);
    }

/* removed
    public static function findIdentityByAccessToken($token)
    {
        throw new NotSupportedException('"findIdentityByAccessToken" is not implemented.');
    }
*/
    /**
     * Finds user by username
     *
     * @param  string      $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        return static::findOne(['username' => $username]);
    }

    /**
     * Finds user by password reset token
     *
     * @param  string      $token password reset token
     * @return static|null
     */
    public static function findByPasswordResetToken($token)
    {
       /* $expire = \Yii::$app->params['user.passwordResetTokenExpire'];
        $parts = explode('_', $token);
        $timestamp = (int) end($parts);
        if ($timestamp + $expire < time()) {
            // token expired
            return null;
        }*/

        return static::findOne([
            'password_reset_token' => $token
        ]);
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->getPrimaryKey();
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }


    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }

    /**
     * Validates password
     *
     * @param  string  $password password to validate
     * @return boolean if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return Yii::$app->security->validatePassword($password, $this->password_hash);
    }

    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     */
    public function setPassword($password)
    {
        $this->password_hash = Yii::$app->security->generatePasswordHash($password);
    }

	public function getPassword()
    {
        return $this->password_hash;
    }


    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey()
    {
        $this->auth_key = Yii::$app->security->generateRandomKey();
    }

    /**
     * Generates new password reset token
     */
    public function generatePasswordResetToken()
    {
        $this->password_reset_token = uniqid(). '_' . time();
    }

    /**
     * Removes password reset token
     */
    public function removePasswordResetToken()
    {
        $this->password_reset_token = null;
    }


    /**
     * Finds out if password reset token is valid
     *
     * @param string $token password reset token
     * @return bool
     */
    public static function isPasswordResetTokenValid($token)
    {
        if (empty($token)) {
            return false;
        }

        $timestamp = (int) substr($token, strrpos($token, '_') + 1);
        $expire = Yii::$app->params['user.passwordResetTokenExpire'];
        return $timestamp + $expire >= time();
    }

	public function updatePassword()
    {
        $user = $this->user;
		echo "<pre>";
		print_r($user);
		die("Debugging...");
        $user->setPassword($this->password);

        return $user->save(false);
    }
	public function updateStatus($cid)
    {
		$data = Yii::$app->request->post();
      Yii::$app->db->createCommand()->update('user', ['status' => $data['User']['status'], 'email' => $data['User']['email'],'security_question' => $data['User']['security_question'], 'fullname' => $data['User']['fullname']],  'id = "'.$cid.'"')->execute();
    }
public static function statusdropdown() {
    $dropdown = array('Moderator' => 'Moderator','Admin' => 'Admin');
    return $dropdown;
   }
    /** EXTENSION MOVIE **/

}

controllers/UserController.php
<?php
namespace app\controllers;

use Yii;
use app\models\User;
use app\models\SearchUser;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

use app\models\PasswordResetRequestForm;
use app\models\ResetPasswordForm;
use app\models\SignupForm;
use app\models\PasswordForm;


class UserController extends \yii\web\Controller
{


    /**
     * @inheritdoc
     */

	public function beforeAction($action)
    {
		//echo "<pre>";
		//print_r($action);
		//die("Debugging...");
        if (in_array($action->id, ['ajax'])) {
            $this->enableCsrfValidation = false;
        }
		if (in_array($action->id, ['delete'])) {
            $this->enableCsrfValidation = false;
        }

        return parent::beforeAction($action);
    }
	public function behaviors()
    {
        return [
            'access'=>[
                'class'=>AccessControl::className(),
				'only' => ['create','update','delete','view','index','profile','requestPasswordReset','resetPassword','Setting','ajax'],
                'rules'=>[
                        [
                        'actions'=>['create','update','delete','view','index','profile','requestPasswordReset','resetPassword','Setting','ajax'],
                        'allow'=>true,
                        'matchCallback'=>function(){
                            return (
                                Yii::$app->user->identity->status=='Admin'
                            );
                        }
                        ],
						[
                         // allow authenticated users
						'actions' => ['index','profile','requestPasswordReset','resetPassword','Setting','ajax'],
                        'allow' => true,
                         'matchCallback'=>function(){
                            return (
                                Yii::$app->user->identity->status=='Moderator'
                            );
                        }
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['get'],
                ],
            ],
        ];
    }

    public function actionIndex()
    {
        $searchModel = new SearchUser();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);

    }

/**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

	public function actionProfile()
    {
        return $this->render('profile');
    }


    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
				//Email Cde
				$message = Yii::$app->mailer->compose();
				if (Yii::$app->user->isGuest) {
					$message->setFrom('info@brainzteck.com');
				} else {
					$message->setFrom(Yii::$app->user->identity->email);
				}

				$body = "<b>Hello ".Yii::$app->request->post()['SignupForm']['username'].", <br> Your login details are below:<br><b>Username</b>:".Yii::$app->request->post()['SignupForm']['username']."<br><b>Password:</b>".Yii::$app->request->post()['SignupForm']['password'];
				$message->setTo(Yii::$app->request->post()['SignupForm']['email'])
					->setSubject('New User Created.')
					->setHtmlBody($body)
					->send();

				Yii::$app->session->setFlash('success', "משתמש נוצר בהצלחה!");
                 return $this->render('create', [
                    'model' => $model,
                ]);
            }
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        if ($model->load(Yii::$app->request->post())) {
			$model->updateStatus($id);
            return $this->redirect(['index', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

   public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->redirect(['request-password-reset']);
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for the provided email address.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
			   throw new BadRequestHttpException($e->getMessage());
        }
     if(!$model->validate()){
		 if(isset($_SESSION['success'])){
		 $msg = $_SESSION['success'];
		 Yii::$app->session->setFlash('success', $msg);
		 return $this->render('resetPassword', [
            'model' => $model,
        ]);
		 }
	 }
        if ($model->load(Yii::$app->request->post())  && $model->resetPassword()) {

            Yii::$app->session->setFlash('success', 'New password saved.');

            return $this->goHome();
        }


        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }

	public function actionSetting()
    {

        $model = new PasswordForm;
        $modeluser = User::findByUsername(Yii::$app->user->identity->email);

        if($model->load(Yii::$app->request->post())){
           /// if($model->validate()){
                try{

                    $modeluser->password = $_POST['PasswordForm']['newpass'];
                    if($modeluser->save()){
                        Yii::$app->getSession()->setFlash(
                            'success','Password changed'
                        );
                        return $this->redirect(['setting']);
                    }else{
                        Yii::$app->getSession()->setFlash(
                            'error','Password not changed'
                        );
                        return $this->redirect(['setting']);
                    }
                }catch(Exception $e){
                    Yii::$app->getSession()->setFlash(
                        'error',"{$e->getMessage()}"
                    );
                    return $this->render('setting',[
                        'model'=>$model
                    ]);
                }
           //}
        }else{
            return $this->render('setting',[
                'model'=>$model
            ]);
        }

	}

	public function actionAjax()
    {
		$UsersModel = new user();
		$email = $UsersModel->updateEmail(Yii::$app->request->post());
    }

}

views/user/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\User */
/* @var $form yii\widgets\ActiveForm */
?>
<?php
 
$this->registerJs(
   '$("document").ready(function(){ 
        $("#new_user").on("pjax:end", function() {
            $.pjax.reload({container:"#user"});  //Reload GridView
        });
    });'
);
?>
<div class="row">
    <div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?= Html::encode($this->title) ?></h3>
            </div>
            <div class="panel-body">
            <?php yii\widgets\Pjax::begin(['id' => 'new_user']) ?>
                <?php $form = ActiveForm::begin([
                    'id' => 'registration-form',
                    'enableAjaxValidation' => true,
                    'enableClientValidation' => false,
					'options' => ['data-pjax' => true ],
                ]); ?>

                <?= $form->field($model, 'email') ?>

                <?= $form->field($model, 'username') ?>

                <?php if ($module->enableGeneratingPassword == false): ?>
                    <?= $form->field($model, 'password')->passwordInput() ?>
                <?php endif ?>

                <?= Html::submitButton(Yii::t('user', 'Create'), ['class' => 'btn btn-success btn-block']) ?>

                <?php ActiveForm::end(); ?>
                <?php yii\widgets\Pjax::end() ?>
            </div>
        </div>
        <p class="text-center">
            <?= Html::a(Yii::t('user', 'Already registered? Sign in!'), ['/user/security/login']) ?>
        </p>
    </div>
</div>

views/user/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\SearchUser */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>


    <?= $form->field($model, 'username') ?>


    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/user/create.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\SignupForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\helpers\ArrayHelper;
use app\models\User;

$this->title = 'הרשמה';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-signup">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>יש למלא את השדות הבאים:</p>

    <div class="row">
    <div class="col-md-4"></div>
        <div class="col-md-4">
           <?php if (Yii::$app->session->hasFlash('success')): ?>
  <div class="alert alert-success alert-dismissable">
  <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
  <h4><i class="icon fa fa-check"></i>נשמר!</h4>
  <?= Yii::$app->session->getFlash('success') ?>
  </div>
           <?php endif; ?>
            <?php $form = ActiveForm::begin(['id' => 'form-signup']); ?>

                <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

                 <?= $form->field($model, 'fullname')->textInput(['autofocus' => true]) ?>
                  <?= $form->field($model, 'security_question')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'email') ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                 <?= $form->field($model, 'status')->dropdownList([
						'Moderator' => 'עובד',
						'Admin' => 'מנהל'
					],
					['prompt'=>'בחר הרשאה']
				); ?>



                <div class="form-group">
                    <?= Html::submitButton('שמור', ['class' => 'btn topbtn', 'name' => 'signup-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
        <div class="col-md-4"></div>
    </div>
</div>
<style>
.help-block-error{ color:red; }
</style>

views/user/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;
use yii\widgets\Pjax;
use app\models\User;
/* @var $this yii\web\View */
/* @var $searchModel app\models\CmsRecordsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

//$this->title = Yii::t('app', 'User');
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="row">
    <div class="col-sm-12 col-md-10">
        <div class="btn-group pull-right m-t-15">
           <?= Html::a(Yii::t('app', 'הוספת משתמש חדש'), ['user/create'], ['class' => 'btn topbtn']) ?>
        </div>
        <h4 class="page-title">משתמשים</h4>
    </div>
</div>
<!-- end row -->

<div class="row">
	<div class="col-lg-12">
 	   <div class="row">
        	<div class="col-lg-12">

<?php Pjax::begin(); ?>
 <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            //['class' => 'yii\grid\SerialColumn'],
            //'id',
            'username',
			'fullname',
			'security_question',
			[
				'attribute' => 'status',
				'label' => 'סוג הרשאה',
				'filter' => User::statusdropdown(),
				'value' => function($model, $index, $dataColumn) {
					$roleDropdown = User::statusdropdown();
					return $roleDropdown[$model->status];
				},
			],
            ['class' => 'yii\grid\ActionColumn',
            'buttons' => [
                'view' => function ($url, $model, $key) {
                    return Html::a ( '<span class="zmdi zmdi-eye" aria-hidden="true"></span> ', ['user/view', 'id' => $model->id] );
                },
				'update' => function ($url, $model, $key) {
                    return Html::a ( '<span class="zmdi zmdi-edit" aria-hidden="true"></span> ', ['user/update', 'id' => $model->id] );
                },
				'delete' => function ($url, $model, $key) {
                    return Html::a ( '<span class="zmdi zmdi-delete" aria-hidden="true"></span> ', ['user/delete', 'id' => $model->id]);
                },
            ],
            'template' => '{update} {view} {delete}'


        ],
        ],
    ]); ?>
<?php Pjax::end(); ?>
</div></div></div></div>

views/user/profile.php
<?php
/* @var $this yii\web\View */
use yii\web\Request;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap\ActiveForm;
use yii\grid\GridView;
use yii\widgets\Pjax;
use  yii\web\Session;
$session = Yii::$app->session;
//$this->title = 'Domains and subsites';
// Modify the XPath query to match the content
?>

<div class="row">
    <div class="col-sm-12">
        <h4 class="page-title">Profile</h4>
    </div>
</div>

<div class="card-box">



<div class="row">
	<div class="col-lg-9">
		<div class="card-box">

    <form action="#" class="form-horizontal">
    <div class="form-group row">
        <label class="col-sm-5 form-control-label">שם משתמש:  </label>
        <div class="col-sm-7"> <?php echo ucfirst(Yii::$app->user->identity->username); ?></div>
    </div>

    <div class="form-group row">
        <label class="col-sm-5 form-control-label">אימייל:  </label>
        <div class="col-sm-7"><a href="#" id="email" data-type="text" data-url="<?php echo Yii::$app->getUrlManager()->createUrl('user/ajax'); ?>"  data-pk="<?php echo $session->get('employee_name'); ?>" data-value="<?php echo Yii::$app->user->identity->email; ?>" data-placement="right" data-placeholder="Required" data-title="<?php echo Yii::$app->user->identity->email; ?>"><?php echo Yii::$app->user->identity->email; ?></a>
        </div>
     </div>

     <div class="form-group row">
        <label class="col-sm-5 form-control-label">הרשאה: </label>
		<div class="col-sm-7"><?php echo Yii::$app->user->identity->status; ?></div>
      </div>

    </form>

</div>
</div></div>



</div>

   <link type="text/css" href="<?php @web?>/themes/unilytics/plugins/x-editable/css/bootstrap-editable.css" rel="stylesheet">
<script src="<?php @web?>/themes/unilytics/plugins/moment/moment.js"></script>
<script src="<?php @web?>/themes/unilytics/plugins/x-editable/js/bootstrap-editable.min.js"></script>
<script>
$(function(){

    //modify buttons style
    $.fn.editableform.buttons =
    '<button type="submit" class="btn btn-primary editable-submit waves-effect waves-light"><i class="zmdi zmdi-check"></i></button>' +
    '<button type="button" class="btn editable-cancel btn-secondary waves-effect"><i class="zmdi zmdi-close"></i></button>';

    //inline

/*
  $('#inline-username').editable({
     type: 'text',
     pk: 1,
     name: 'username',
     title: 'Enter username',
     mode: 'inline'
   });*/

    $('#email').editable({
      validate: function(value) {
       if($.trim(value) == '') return 'This field is required';
     },
     mode: 'inline'
   });



  });
</script>

views/user/requestPasswordResetToken.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\PasswordResetRequestForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Request password reset';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-request-password-reset">
  <?php if (Yii::$app->session->hasFlash('success')): ?>
  <div class="alert alert-success alert-dismissable">
  <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
  <h4><i class="icon fa fa-check"></i>Saved!</h4>
  <?= Yii::$app->session->getFlash('success') ?>
  </div>
  <?php endif; ?>

    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out your email. A link to reset password will be sent there.</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'request-password-reset-form']); ?>

                <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Send', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

views/user/resetPassword.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ResetPasswordForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Reset password';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-reset-password">
    <h1><?= Html::encode($this->title) ?></h1>
  <?php if (Yii::$app->session->hasFlash('success')): ?>
  <div class="alert alert-success alert-dismissable">
  <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
  <?= Yii::$app->session->getFlash('success') ?>
  </div>
  <?php endif; ?>
    <p>Please choose your new password:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'reset-password-form']); ?>

                <?= $form->field($model, 'password')->passwordInput(['autofocus' => true]) ?>
                
                <div class="form-group field-resetpasswordform-password required has-error">
                <label class="control-label" for="resetpasswordform-password">Confirm Password</label>
                <input id="confirm_password" class="form-control" name="confirmPassword" value="" autofocus="" aria-required="true" aria-invalid="true" type="password" required="required">
                
                <span id="indicator" style="display:none">Password not matching.</span>
                </div>

                <div class="form-group">
                    <?= Html::submitButton('Save', ['class' => 'btn btn-primary', 'id' => 'regbtn']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>
<script>

$('#confirm_password').keyup(function(){
    var pass    =   $('#resetpasswordform-password').val();
    var cpass   =   $('#confirm_password').val();
    if(pass!=cpass){
		$('#indicator').css({display:'block'});
        $('#indicator').css({color:'red'});
        $('#regbtn').attr({disabled:true});
    }
    else{
        $('#indicator').attr({color:'green'});
		$('#indicator').css({display:'none'});
        $('#regbtn').attr({disabled:false});
    }
});

</script>

views/user/setting.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Change Password';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="site-changepassword">
    <h1><?= Html::encode($this->title) ?></h1>
   
    <p>Please fill out the following fields to change password :</p>
    <?php if (Yii::$app->session->hasFlash('success')): ?>
  <div class="alert alert-success alert-dismissable">
  <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
  <h4><i class="icon fa fa-check"></i>Saved!</h4>
  <?= Yii::$app->session->getFlash('success') ?>
  </div>
  <?php endif; ?>
   <?php if (Yii::$app->session->hasFlash('error')): ?>
  <div class="alert alert-error alert-dismissable">
  <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
  <h4><i class="icon fa fa-check"></i>Error!</h4>
  <?= Yii::$app->session->getFlash('error') ?>
  </div>
  <?php endif; ?>
    <?php $form = ActiveForm::begin([
        'id'=>'changepassword-form',
        'options'=>['class'=>'form-horizontal'],
        'fieldConfig'=>[
            'template'=>"{label}\n<div class=\"col-lg-3\">
                        {input}</div>\n<div class=\"col-lg-5\">
                        {error}</div>",
            'labelOptions'=>['class'=>'col-lg-2 control-label'],
        ],
    ]); ?>
        <?= $form->field($model,'oldpass',['inputOptions'=>[
            'placeholder'=>'Old Password'
        ]])->passwordInput() ?>
       
        <?= $form->field($model,'newpass',['inputOptions'=>[
            'placeholder'=>'New Password'
        ]])->passwordInput() ?>
       
        <?= $form->field($model,'repeatnewpass',['inputOptions'=>[
            'placeholder'=>'Repeat New Password'
        ]])->passwordInput() ?>
       
        <div class="form-group">
            <div class="col-lg-offset-2 col-lg-11">
                <?= Html::submitButton('Change password',[
                    'class'=>'btn btn-primary'
                ]) ?>
            </div>
        </div>
    <?php ActiveForm::end(); ?>
</div> 

views/user/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Users'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'username',
			'fullname',
            'email:email',
            'status',
            'created_at',
            'updated_at',
        ],
    ]) ?>

</div>