models/Food.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "food".
 *
 * @property int $food_id
 * @property int $container_id
 * @property string $fish_to
 * @property string $day_of_week
 * @property string $food_type
 * @property string $unit
 * @property string $amount
 * @property string $actual_unit
 * @property string $actual_amount
 * @property string $comment
 * @property string $created_date
 * @property string $updated_date
 * @property int $created_by
 */
class Food extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'food';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['container_id', 'food_type', 'created_date', 'updated_date', 'unit', 'fish_to', 'food_type', 'amount'], 'required'],
            [['container_id'], 'integer'],
            [['unit', 'actual_unit', 'comment', 'comment_w','created_by'], 'string'],
            [['created_date', 'updated_date'], 'safe'],
            [['fish_to', 'food_type', 'amount', 'actual_amount'], 'string', 'max' => 55],
            [['day_of_week'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'food_id' => Yii::t('app', 'Food ID'),
            'container_id' => Yii::t('app', 'מיכל'),
            'fish_to' => Yii::t('app', 'עבור'),
            'day_of_week' => Yii::t('app', 'יום בשבוע'),
            'food_type' => Yii::t('app', 'סוג מזון'),
            'unit' => Yii::t('app', 'יחידות'),
            'amount' => Yii::t('app', 'כמות'),
            'actual_unit' => Yii::t('app', 'Actual Unit'),
            'actual_amount' => Yii::t('app', 'סטטוס האכלה'),
            'comment' => Yii::t('app', 'הערה'),
            'comment_w' => Yii::t('app', 'הערת מאכיל'),
            'created_date' => Yii::t('app', 'תאריך יצירה'),
            'updated_date' => Yii::t('app', 'Updated Date'),
            'created_by' => Yii::t('app', 'Created By'),
        ];
    }

    /**
     * {@inheritdoc}
     * @return FoodQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new FoodQuery(get_called_class());
    }

	public function GetFishName($fid){
	          if($fid=='All'){
			  return "All";
			  }else{
		       $selQry = Yii::$app->db->createCommand("SELECT name from fish where fid='".$fid."'");
                $result = $selQry->queryOne();
				 return  $result['name'];
			  }
	}

	public static function containerdropdown() {
       $selQry2       = Yii::$app->db->createCommand("SELECT cid, container_name FROM containers");
       $result = $selQry2->queryAll();
    foreach ($result as $model) {
        $dropdown[$model['cid']] = $model['container_name'];
    }
    return $dropdown;
   }

   public static function daydropdown() {
    $dropdown = array('Sunday'=>'Sunday','Monday'=>'Monday','Tuesday'=>'Tuesday','Wednesday'=>'Wednesday','Thursday'=>'Thursday','Friday'=>'Friday','Saturday'=>'Saturday');
    return $dropdown;
   }

   public static function unitdropdown() {
    $dropdown = array('גרם'=>'גרם','קילוגרם'=>'קילוגרם','יחידות'=>'יחידות');
    return $dropdown;
   }

	public static function foodtypedropdown() {
       $selQry2       = Yii::$app->db->createCommand("SELECT foodt_id, food_type FROM food_type");
       $result = $selQry2->queryAll();
    foreach ($result as $model) {
        $dropdownt[$model['foodt_id']] = $model['food_type'];
    }
    return $dropdownt;
   }
}

controllers/FoodController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Food;
use app\models\FoodSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Response;
use yii\helpers\Json;
use  yii\web\Session;
use yii\helpers\Url;


/**
 * FoodController implements the CRUD actions for Food model.
 */
class FoodController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

	public function beforeAction($action) {
		$session = Yii::$app->session;
		if ($session->get('sleep'))
            $this->redirect(array('site/second'));
			if (!$session->get('employee_name'))
            $this->redirect(array('site/second'));

    if($action->id == "index")
        $this->enableCsrfValidation = false;
	if($action->id == "tabscreate")
        $this->enableCsrfValidation = false;
	if($action->id == "savefood")
        $this->enableCsrfValidation = false;
	if($action->id == "saveactualamount")
        $this->enableCsrfValidation = false;
	if($action->id == "deletefood")
        $this->enableCsrfValidation = false;
	if($action->id == "foodupdate")
        $this->enableCsrfValidation = false;
	if($action->id == "updatefood")
        $this->enableCsrfValidation = false;
	if($action->id == "updatedfood")
        $this->enableCsrfValidation = false;

    return parent::beforeAction($action);
    }

    /**
     * Lists all Food models.
     * @return mixed
     */
    public function actionIndex()
    {
		$session = Yii::$app->session;
        $searchModel = new FoodSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
		$container_id = $session->get('cid');
		$data = $searchModel->getContainerData($container_id);
		$current_update = $searchModel->getCurrentUpdate($container_id);
		$last_update = $searchModel->getLastUpdate($container_id);



        $html = $this->renderPartial('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
			'data' => $data,
			'current_update' => $current_update,
			'last_update' => $last_update,
        ]);
		return Json::encode($html);
    }

	public function actionTabscreate() {
		  $model = new Food();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->food_id]);
        }

        return $this->renderPartial('create', [
            'model' => $model,
        ]);
    }

    /**
     * Displays a single Food model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Food model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Food();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->food_id]);
        }

        return $this->renderPartial('create', [
            'model' => $model,
        ]);

    }

    /**
     * Updates an existing Food model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->food_id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Food model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Food model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Food the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Food::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
	public function actionSavefood()
    {
        $post = Yii::$app->request->post();
		 $selQry     = Yii::$app->db->createCommand("SELECT cid from containers");
         $result = $selQry->queryAll();
		 foreach($result as $rows){
	Yii::$app->db->createCommand('INSERT INTO food (container_id, food_type, unit, amount, actual_unit, actual_amount,commemt, created_date, updated_date, created_by) VALUES (:container_id,:food_type,:unit,:amount,:actual_unit, :actual_amount,:comment, :created_date, :updated_date, :created_by)', array(
    ':container_id' => $rows['cid'],
	':food_type' => $post['food_type'],
	':unit' => $post['unit'],
	':amount' => $post['amount'],
	':actual_unit' => $post['actual_unit'],
	':actual_amount'  => $post['actual_amount'],
  	':comment'  => $post['comment'],
	':created_date' => $post['created_date'],
	':updated_date' => $post['updated_date'],
	':created_by' => $post['created_by'],
	))->execute();
	Yii::$app->db->createCommand('INSERT INTO logs (what_did, who_did, container_id, action_date) VALUES (:what_did,:who_did,:container_id, :action_date)', array(
    ':what_did' => "Updated food table For ",
	':who_did' => $post['created_by'],
	':container_id' => $rows['cid'],
	':action_date' => $post['created_date'],
	))->execute();
		 }
    }

	public function actionUpdatedfood()
    {
        $post = Yii::$app->request->post();
		$session = Yii::$app->session;
		Yii::$app->db->createCommand()->update('food', ['food_type' => $post['food_type'],'unit' => $post['unit'],'amount' => $post['amount'],'actual_amount' => $post['actual_amount'],'updated_date' => $post['updated_date'], 'created_by' => $session->get('employee_name')], 'food_id = "'.$post['food_id'].'"')->execute();

	Yii::$app->db->createCommand('INSERT INTO logs (what_did, who_did, container_id, action_date) VALUES (:what_did,:who_did,:container_id, :action_date)', array(
    ':what_did' => "Updated food table For ",
	':who_did' => $post['created_by'],
	':container_id' => $post['container_id'],
	':action_date' => $post['created_date'],
	))->execute();
    }


	public function actionSaveactualamount()
    {
        $post = Yii::$app->request->post();
		$session = Yii::$app->session;
		if(!empty($post['actual_amount'])){
		Yii::$app->db->createCommand()->update('food', ['actual_amount' => $post['actual_amount'], 'updated_date'=>date('Y-m-d H:i:s'), 'created_by' => $session->get('employee_name')], 'food_id = "'.$post['food_id'].'"')->execute();
		}
		if(!empty($post['actual_unit'])){
		Yii::$app->db->createCommand()->update('food', ['actual_unit' => $post['actual_unit'], 'updated_date'=>date('Y-m-d H:i:s'), 'created_by' => $session->get('employee_name')], 'food_id = "'.$post['food_id'].'"')->execute();
		}
		if(!empty($post['comment'])){
		Yii::$app->db->createCommand()->update('food', ['comment' => $post['comment'], 'updated_date'=>date('Y-m-d H:i:s'), 'created_by' => $session->get('employee_name')], 'food_id = "'.$post['food_id'].'"')->execute();
		}
    if(!empty($post['comment_w'])){
		Yii::$app->db->createCommand()->update('food', ['comment_w' => $post['comment_w'], 'updated_date'=>date('Y-m-d H:i:s'), 'created_by' => $session->get('employee_name')], 'food_id = "'.$post['food_id'].'"')->execute();
		}

		 $selQry     = Yii::$app->db->createCommand("SELECT * from food where food_id='".$post['food_id']."'");
         $rows = $selQry->queryOne();

		 $selQry2     = Yii::$app->db->createCommand("SELECT f_history from food_history where food_id='".$post['food_id']."' AND created_date='".date('Y-m-d')."' AND container_id ='".$rows['container_id']."'");
         $row = $selQry2->queryOne();
		 $created_by =  $session->get('employee_name');
		if(!empty($row['f_history'])){
		Yii::$app->db->createCommand()->update('food_history', ['comment' => $post['comment'],'comment_w' => $post['comment_w'], 'actual_amount' => $post['actual_amount'], 'updated_date'=>date('Y-m-d H:i:s'),  'created_by' => $session->get('employee_name')], 'food_id = "'.$post['food_id'].'" AND created_date="'.date('Y-m-d').'"')->execute();
		}else{
		Yii::$app->db->createCommand('INSERT INTO food_history (food_id, container_id, fish_to, day_of_week, food_type, unit, amount, actual_unit, actual_amount,comment,comment_w, created_date, updated_date, created_by) VALUES (:food_id, :container_id, :fish_to, :day_of_week, :food_type,:unit,:amount,:actual_unit, :actual_amount, :comment, :comment_w, :created_date, :updated_date, :created_by)', array(
	':food_id' => $rows['food_id'],
    ':container_id' => $rows['container_id'],
	':fish_to' => $rows['fish_to'],
	':day_of_week' => $rows['day_of_week'],
	':food_type' => $rows['food_type'],
	':unit' => $rows['unit'],
	':amount' => $rows['amount'],
	':actual_unit' => '',
	':actual_amount'  => $post['actual_amount'],
	':comment'  => $post['comment'],
  ':comment_w'  => $post['comment_w'],
	':created_date' => date('Y-m-d'),
	':updated_date' => date('Y-m-d H:i:s'),
	':created_by' => $session->get('employee_name'),
	))->execute();

controllers/FoodsController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Food;
use app\models\FoodSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * FoodsController implements the CRUD actions for Food model.
 */
class FoodsController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

	public function beforeAction($action) 
	{ 
	$session = Yii::$app->session;
		if ($session->get('sleep'))
            $this->redirect(array('site/second'));
        if (!$session->get('employee_name'))
            $this->redirect(array('site/second'));
		$this->enableCsrfValidation = false; 
		return parent::beforeAction($action); 
	}
    /**
     * Lists all Food models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new FoodSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Food model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Food model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Food();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index', 'id' => $model->food_id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Food model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->food_id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Food model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Food model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Food the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Food::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
	public function actionLists($id)
    {				
        $posts = \app\models\Fish::find()
				->where(['container_id' => $id])
				->orderBy('fid DESC')
				->all();
				$html = "";
		if (!empty($posts)) {
			$html .="<option value='ALL'>All</option>";
			foreach($posts as $post) {
				$html .="<option value='".$post->fid."'>".$post->name."</option>";
			}
			echo $html;
		} else {
			echo "<option>-</option>";
		}
		
    }
}

views/food/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Food */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="food-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'container_id')->textInput() ?>

    <?= $form->field($model, 'food_type')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'unit')->dropDownList([ 'Gram' => 'Gram', 'Ponds' => 'Ponds', 'Kg' => 'Kg', ], ['prompt' => '']) ?>

    <?= $form->field($model, 'amount')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'actual_unit')->dropDownList([ 'Gram' => 'Gram', 'Ponds' => 'Ponds', 'Kg' => 'Kg', ], ['prompt' => '']) ?>

    <?= $form->field($model, 'actual_amount')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'comment')->textInput() ?>

    <?= $form->field($model, 'created_date')->textInput() ?>

    <?= $form->field($model, 'updated_date')->textInput() ?>

    <?= $form->field($model, 'created_by')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Save'), ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/food/create.php
<?php

use yii\helpers\Html;
use  yii\web\Session;
use yii\helpers\Url;
$session = Yii::$app->session;

/* @var $this yii\web\View */
/* @var $model app\models\Food */

$this->title = Yii::t('app', 'Create Food');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Foods'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="row">
	<div class="col-sm-12">
		<div class="btn-group pull-right m-t-15">
         <a class="btn topbtn" href="#tab=w0-tab2" onclick="return backfood();">Back</a>
        </div>
    </div>
</div>

<div class="row">
<div class="col-sm-12">
<div class="col-sm-4"></div>
<div class="col-sm-4">
<form id="w0" action="" method="post">


    <div class="form-group field-fish-name required">
		<label class="control-label" for="fish-name">Food Type</label>
		<input id="food_type" class="form-control" name="food_type" maxlength="55" aria-required="true" type="text">

		<div class="help-block"></div>
	</div>
    <div class="form-group field-fish-s_name required">
		<label class="control-label" for="fish-s_name">Unit</label>
		<select class="form-control" id="unit" name="unit" style="height: 36px;">
			<option value="Gram">Gram</option>
			<option value="Ponds">Ponds</option>
			<option value="Kg">Kg</option>
		  </select>

    </div>

	<div class="form-group field-fish-s_name required">
		<label class="control-label" for="fish-s_name">Amount</label>
		<input id="amount" class="form-control" name="amount" maxlength="255" aria-required="true" type="text">

		<div class="help-block"></div>
    </div>

    <div class="form-group field-fish-amount required">
		<label class="control-label" for="fish-amount">Actual Unit</label>
		<select class="form-control" id="actual_unit" name='actual_unit' style="height: 36px;">
			<option value="Gram">Gram</option>
			<option value="Ponds">Ponds</option>
			<option value="Kg">Kg</option>
		  </select>

    </div>

	<div class="form-group field-fish-s_name required">
		<label class="control-label" for="fish-s_name">Actual Amount</label>
		<input id="actual_amount" class="form-control" name="actual_amount" maxlength="255" aria-required="true" type="text">

		<div class="help-block"></div>
    </div>

    <div class="form-group field-fish-created_date required">

		<input id="created_date" class="form-control" name="created_date" value="<?php echo date ("Y-m-d"); ?>" type="hidden">
		<div class="help-block"></div>
	</div>
    <div class="form-group field-fish-updated_date required">
		<input id="updated_date" class="form-control" name="updated_date" value="<?php echo date ("Y-m-d H:i:s"); ?>" type="hidden">
		<div class="help-block"></div>
	</div>

    <div class="form-group"><button type="button" class="btn topbtn fa fa-floppy-o" onclick="return savefood();"> שמור </button></div>

    </form>
</div>
<div class="col-sm-4"></div>

</div>
</div>
</div>
<script>
	function backfood(){
        $("#food").trigger('click');
	}
	function savefood(){
		if($("#food_type").val() ==''){
			alert("Please Enter Food Type.");
			$("#food_type").focus();
			return false;
		}
		if($("#amount").val() ==''){
			alert("Please Enter Amount.");
			$("#amount").focus();
			return false;
		}
		if($("#actual_amount").val() ==''){
			alert("Please Enter Actual Amount.");
			$("#actual_amount").focus();
			return false;
		}

		food_type  = $("#food_type").val();
		unit       = $("#unit").val();
		amount     = $("#amount").val();
		actual_unit    = $("#actual_unit").val();
		actual_amount  = $("#actual_amount").val();

		created_date     = $("#created_date").val();
		updated_date     = $("#updated_date").val();
		$.ajax({
       method: "POST",
          url: "<?php echo Url::to(['food/savefood']); ?>",
         data: { container_id: "<?php echo $session->get('cid'); ?>", food_type: food_type, unit:unit,  amount:amount, actual_unit:actual_unit,  actual_amount:actual_amount, created_date:created_date, updated_date:updated_date, created_by:"<?php echo $session->get('employee_name'); ?>"}
        })
       .done(function( msg ) {
		   alert("Food has been saved.");
         setTimeout(function() {
        $("#food").trigger('click');
    },1);
       });
	}
</script>

views/food/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use  yii\web\Session;
use app\models\Food;
use app\models\Lss;
use yii\helpers\Url;
$session = Yii::$app->session;
$foodTable = new Food;
$foodTable = new Lss;

/* @var $this yii\web\View */
/* @var $searchModel app\models\FoodSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Foods');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="row">

	<div class="col-sm-1 col-md-1 col-lg-12">
		<div class="btn-group pull-right">
		 תאריך:  <?php echo $current_update; ?>
		</div>
    </div>
</div>

<div class="row">



    <form>
  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th style="text-align:center;">סוג מזון</th>
        <th style="text-align:center;">יום בשבוע</th>
        <th style="text-align:center;">עבור</th>
        <th style="text-align:center;">כמות</th>
        <th style="text-align:center;">יחידות</th>
        <th style="text-align:center;">סטטוס האכלה</th>
		<!--th style="text-align:center;">Actual Unit:</th-->
        <th style="text-align:center;">הערה</th>
				<th style="text-align:center;">הערת מאכיל</th>
      </tr>
    </thead>
    <tbody>
	<?php
	$commaString = array();

	foreach($data as $rows){
	if( date("l")==$rows['day_of_week']){
		$commaString[] = $rows['food_id'];
		$oDate = strtotime($rows['updated_date']);
       $sDate = date("Y-m-d",$oDate);
	   $curDate  = date("Y-m-d");
	?>
      <tr data-key="<?php echo $rows['food_id']; ?>">
        <td><?php echo $foodTable->getFoodType($rows['food_type']); ?></td>
        <td><?php echo $rows['day_of_week']; ?></td>
        <td><?php echo $foodTable->GetFishName($rows['fish_to']); ?></td>
        <td><?php echo $rows['amount']; ?></td>
				<td><?php echo $rows['unit']; ?></td>

		<td>
		  <select class="form-control" id="actualamount_<?php echo $rows['food_id']; ?>">
			<option value="" <?php if($sDate !=$curDate){ echo "disabled selected"; }?>>בחר סטטוס</option>
			<option value="אכל" <?php if($sDate ==$curDate){ if($rows['actual_amount']=='אכל'){ echo "selected"; }}?>>אכל</option>
			<option value="לא אכל" <?php if($sDate ==$curDate){if($rows['actual_amount']=='לא אכל'){ echo "selected"; }}?>>לא אכל</option>
			<option value="אכל חלקית" <?php if($sDate ==$curDate){if($rows['actual_amount']=='אכל חלקית'){ echo "selected"; }}?>>אכל חלקית</option>
            <option value="אכל פחות" <?php if($sDate ==$curDate){ if($rows['actual_amount']=='אכל פחות'){ echo "selected"; }}?>>אכל פחות</option>
			<option value="אכל יותר" <?php if($sDate ==$curDate){ if($rows['actual_amount']=='אכל יותר'){ echo "selected"; }}?>>אכל יותר</option>

		  </select>
		</td>
      	<td><textarea  disabled class="form-control" rows="1" id="comment_<?php echo $rows['food_id']; ?>"><?php if(!empty($rows['comment'])){ echo $rows['comment']; }?></textarea></td>
			<td><textarea class="form-control" rows="1" id="comment_w_<?php echo $rows['food_id']; ?>"></textarea></td>
        </tr>

	<?php }  } ?>
    <?php
	$cnt = sizeof($commaString);
	if($cnt >0){ ?>
	<tr><td colspan="12" ><button class="btn savelss fa fa-floppy-o" onclick="return backfoodss();" style="width:30%"> שמור </button></td></tr>
<?php }else{echo '<tr><td colspan="8" st>לא נמצא מזון להאכלה</td></tr>';} ?>
    </tbody>
  </table>
  <?php $strArr = implode(",", $commaString);?>
  <input type="hidden" id="hid" value="<?php echo $strArr; ?>" />
  </form>
 <?php if($cnt >0){ ?>
  <?php echo date('D M j G:i:s T Y', strtotime($last_update)); ?>         Last Update
  <?php } ?>



</div>
<script>
function backfoodss(){
    str = $("#hid").val();
	var myarray = str.split(',');

for(var i = 0; i < myarray.length; i++)
{
	food_id = myarray[i];
    if($("#actualamount_"+food_id).val()==''){
		alert("Please enter actual amount.");
		$("#actualamount_"+food_id).focus();
		return false;
		}
	comment = $("#comment_"+food_id).val();
   actual_amount = $("#actualamount_"+food_id).val();
	 comment_w = $("#comment_w_"+food_id).val();
   //actual_unit   = $("#actualunit_"+food_id).val();
   $.ajax({
       method: "POST",
          url: "<?php echo Url::to(['food/saveactualamount']); ?>",
         data: { food_id:food_id,  actual_amount:actual_amount, comment:comment, comment_w:comment_w}
        })
       .done(function( msg ) {

       });
}
 alert("ההאכלה נשמרה בהצלחה!");
		 setTimeout(function() {
        $("#food").trigger('click');
    },1);
	return false;
}


</script>