models/Vetd.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "vet_diag".
 *
 * @property int $vedt_id
 * @property int $container_id
 * @property string $diagnostic_for
 * @property string $comments
 * @property string $date_created
 */
class Vetd extends \yii\db\ActiveRecord
{
    public $upload_file;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'vet_diagnostic';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['container_id', 'diagnostic_for', 'diagnostic_name','diagnostic_type' , 'comments', 'date_created'], 'required'],
            [['container_id'], 'integer'],
            [['comments'], 'string'],
            [['date_created'], 'safe'],
            [['diagnostic_for','diagnostic_name','diagnostic_type', 'image'], 'string', 'max' => 255],
            [['upload_file'],'file', 'skipOnEmpty' => true ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'vedt_id' => Yii::t('app', 'Vetd ID'),
            'container_id' => Yii::t('app', 'Container ID'),
            'diagnostic_for' => Yii::t('app', 'Diagnostic For'),
            'diagnostic_name' => Yii::t('app', 'Diagnostic Name'),
            'diagnostic_type' => Yii::t('app', 'Diagnostic Type'),
            'comments' => Yii::t('app', 'Comments'),
            'date_created' => Yii::t('app', 'Date'),
            'image' => Yii::t('app', 'Image'),
            'upload_file' =>  Yii::t('app','Upload File')
        ];
    }

    /**
     * {@inheritdoc}
     * @return VetdQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new VetdQuery(get_called_class());
    }
    

	public function getFishData($container_id){
		$selQry = Yii::$app->db->createCommand("SELECT * from fish where container_id='".$container_id."'");
        return $result = $selQry->queryAll();
	}

  public function getFishDataDrop($cnt){
           $selQry    = Yii::$app->db->createCommand("SELECT DISTINCT name,fid from fish where container_id =$cnt group by 1");
               return $result = $selQry->queryAll();
  }

	public static function getFish($id){
		if($id==0){
			return "All Container";
		}else{
        $selQry2 = Yii::$app->db->createCommand("SELECT name FROM fish where fid= '".$id."'");
		$result = $selQry2->queryOne();
			if(!empty($result)){
				return $result['name'];
			}
		}

        return null;
    }

	public static function getDiagonoName($id){
		$selQry = Yii::$app->db->createCommand("SELECT d_name from diagnostic where d_id='".$id."'");
        $result = $selQry->queryOne();
		if(!empty($result['d_name'])){
		return $result['d_name'];
		}else{
			return "";
		}
	}
}

controllers/VetdController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Vetd;
use app\models\VetdSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Response;
use yii\helpers\Json;
use  yii\web\Session;
use yii\helpers\Url;
use yii\web\UploadedFile;


/**
 * VetController implements the CRUD actions for Vet model.
 */
class VetdController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

	public function beforeAction($action) {
		$session = Yii::$app->session;
		if ($session->get('sleep'))
            $this->redirect(array('site/second'));

    if($action->id == "index")
        $this->enableCsrfValidation = false;
	if($action->id == "addcomment")
        $this->enableCsrfValidation = false;
	if($action->id == "savecomment")
        $this->enableCsrfValidation = false;
	if($action->id == "updatecomment")
        $this->enableCsrfValidation = false;
	if($action->id == "deletecomment")
        $this->enableCsrfValidation = false;
	if($action->id == "tabsupdate")
        $this->enableCsrfValidation = false;
    if($action->id == "getsecond")
        $this->enableCsrfValidation = false;

    return parent::beforeAction($action);
    }
    /**
     * Lists all Vet models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new VetdSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        $html = $this->renderPartial('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
		return Json::encode($html);
    }

    /**
     * Displays a single Vet model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }
   public function actionAddcomment() {
		  $model = new Vetd();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->vedt_id]);
        }

        return $this->renderPartial('create', [
            'model' => $model,
        ]);
    }
    /**
     * Creates a new Vet model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Vetd();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->vedt_id]);
        }


        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Vet model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->vedt_id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Vet model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }
public function actionUpload()
{
    $fileName = 'image';
    $uploadPath = 'vetd_files';

    if (isset($_FILES[$fileName])) {
        $file = \yii\web\UploadedFile::getInstanceByName($fileName);

        //Print file data
        //print_r($file);

        if ($file->saveAs($uploadPath . '/' . $file->name)) {
		   
            //Now save file data to database

            echo \yii\helpers\Json::encode($file);
        }
    }

    return false;
}
    /**
     * Finds the Vet model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Vetd the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Vetd::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
	public function actionSavecomment()
    {
	$post = Yii::$app->request->post();

	Yii::$app->db->createCommand('INSERT INTO vet_diagnostic (container_id, diagnostic_for, diagnostic_name, diagnostic_type, image, comments, date_created, updated_date, created_by) VALUES (:container_id,:diagnostic_for, :diagnostic_name, :diagnostic_type, :image, :comments,  :date_created, :updated_date, :created_by)', array(
  ':container_id' => $post['container_id'],
	':diagnostic_for' => $post['diagnostic_for'],
	':diagnostic_name' => $post['diagnostic_name'],
	':diagnostic_type' => $post['diagnostic_type'],
	':image' => $post['image'],
	':comments' => $post['comments'],
	':date_created' => $post['created_date'],
	':updated_date' => $post['updated_date'],
	':created_by' => $post['created_by'],
	))->execute();

	Yii::$app->db->createCommand('INSERT INTO logs (what_did, who_did, container_id, action_date) VALUES (:what_did,:who_did,:container_id, :action_date)', array(
    ':what_did' => "Added Vet Diagnostic For ",
	':who_did' => $post['created_by'],
	':container_id' => $post['container_id'],
	':action_date' => $post['created_date'],
	))->execute();



    }

   public function actionUpdatecomment()
    {
        $model = new Vetd();
        $post = Yii::$app->request->post();
		Yii::$app->db->createCommand()->update('vet_diagnostic', ['diagnostic_for' => $post['diagnostic_for'], 'diagnostic_name' => $post['diagnostic_name'], 'diagnostic_type' => $post['diagnostic_type'], 'comments' => $post['comments'], 'updated_date' => $post['updated_date']], 'vedt_id = "'.$post['vet_id'].'"')->execute();
		Yii::$app->db->createCommand('INSERT INTO logs (what_did, who_did, container_id, action_date) VALUES (:what_did,:who_did,:container_id, :action_date)', array(
    ':what_did' => "Updared Vet Diagonostic Report For ",
	':who_did' => $post['created_by'],
	':container_id' => $post['container_id'],
	':action_date' => $post['created_date'],
	))->execute();
    }
  public function actionDeletecomment()
    {
		$post = Yii::$app->request->post();
		$id  = $post['fid'];
        Yii::$app->db->createCommand('DELETE FROM vet_diagnostic WHERE vedt_id='.$id.'')->execute();
		$this->actionIndex();
    }
	public function actionTabsupdate() {
		  $model = new Vetd();
         $post = Yii::$app->request->post();
		 $id = $post['fid'];
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'vedt_id' => $model->vedt_id]);
        }

        return $this->renderPartial('update', [
            'model' => $model,
        ]);
    }

	public function actionGetsecond(){

		 $qry = "";
		 $post = Yii::$app->request->post();
		 $id = $post['id'];
		 $dropdown  = '';
	     if($id){
		   $qry = " where parent ='".$id."'";
		   }
            $selQry2       = Yii::$app->db->createCommand("SELECT * from diagnostic $qry");
            $result = $selQry2->queryAll();
			foreach ($result as $model) {
				$dropdown .= '<option value="'.$model['d_id'].'">'.$model['d_name'].'</option>';
			}
			return $dropdown;
		}

}

views/vetd/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Vet */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="vetd-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'container_id')->textInput() ?>

    <?= $form->field($model, 'diagnostic_for')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'diagnostic_name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'diagnostic_type')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'comments')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'image')->fileinput() ?>

    <?= $form->field($model, 'date_created')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Save'), ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/vetd/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\VetSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="vet-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'vet_id') ?>

    <?= $form->field($model, 'container_id') ?>

    <?= $form->field($model, 'diagnostic_for') ?>

    <?= $form->field($model, 'comments') ?>

    <?= $form->field($model, 'date_created') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/vetd/create.php
<?php

use yii\helpers\Html;
use  yii\web\Session;
use yii\helpers\Url;
use app\models\Diagnostic;
use yii\widgets\ActiveForm;
$session = Yii::$app->session;

/* @var $this yii\web\View */
/* @var $model app\models\Food */

$this->title = Yii::t('app', 'Create Vetd');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Vetd'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

$post = Yii::$app->request->post();
$data = $model->getFishDataDrop($post['cid']);
$diagnoModel  = new Diagnostic();
$parentDrop = $diagnoModel->getParentData();
?>
<div class="row">
	<div class="col-sm-12">
	     <h1>אבחנה חדשה</h1>
		<div class="btn-group pull-right m-t-15">
         <a class="btn topbtn fa fa-chevron-right" href="#tab=w0-tab2" onclick="return backfood();"> חזור </a>
        </div>
    </div>
</div>

<div class="row">
<div class="col-sm-12">
<div class="col-sm-4"></div>
<div class="col-sm-4">
<form id="w0" action="" method="post">
     <div class="form-group field-fish-s_name required">
		<label class="control-label" for="fish-s_name">אבחנה ראשית</label>
		<select class="form-control" id="diagnostic_main" name="diagnostic_main" style="height: 36px;" onchange="setseconddropdown(this.value);">
        <option value="0">בחר אבחנה ראשית</option>
		  <?php foreach($parentDrop as $parentDrops){ ?>
			<option value="<?php echo $parentDrops['d_id']; ?>"><?php echo $parentDrops['d_name']; ?></option>
		  <?php } ?>

		  </select>

    </div>

    <div class="form-group field-fish-s_name required">
		<label class="control-label" for="fish-s_name">אבחנה משנית</label>
		<select class="form-control" id="diagnostic_second" name="diagnostic_second" style="height: 36px;">
			<option value="0">בחר אבחנה משנית</option>
		  </select>

    </div>

    <div class="form-group field-fish-s_name required">
		<label class="control-label" for="fish-s_name">עבור</label>
		<select class="form-control" id="diagnostic_for" name="diagnostic_for" style="height: 36px;">
		  <?php foreach($data as $fishDrop){ ?>
			<option value="<?php echo $fishDrop['fid']; ?>"><?php echo $fishDrop['name']; ?></option>
		  <?php } ?>
			<option value="0">All Container</option>
		  </select>

    </div>

	<input type="file" name = "image" id="image" />



    <div class="form-group field-fish-name required">
		<label class="control-label" for="fish-name">הערה</label>
		<textarea cols="5" rows="5" name="comments" class="form-control" id="comments"></textarea>
		<div class="help-block"></div>
	</div>

    <div class="form-group field-fish-created_date required">
		<input id="created_date" class="form-control" name="created_date" value="<?php echo date ("Y-m-d"); ?>" type="hidden">
		<input id="updated_date" class="form-control" name="updated_date" value="<?php echo date ("Y-m-d H:i:s"); ?>" type="hidden">
	</div>


    <div class="form-group"><button type="button" class="btn topbtn fa fa-floppy-o" onclick="return savediagno();"> שמור </button></div>

    </form>
</div>
<div class="col-sm-4"></div>

</div>
</div>
</div>
<script>

    function setseconddropdown(id){
		$.ajax({
       method: "POST",
          url: "<?php echo Url::to(['vetd/getsecond']); ?>",
         data: {id: id}
        })
       .done(function( msg ) {
		 $("#diagnostic_second").html(msg);
       });
		}
	function backfood(){
        $("#vetd").trigger('click');
	}

	function savediagno(){
		if($("#diagnostic_main").val() ==''){
			alert("Please Select Main Diagnostic.");
			$("#diagnostic_main").focus();
			return false;
		}
		if($("#diagnostic_second").val() ==''){
			alert("Please Select Second Diagnostic.");
			$("#diagnostic_second").focus();
			return false;
		}

		if($("#diagnostic_for").val() ==''){
			alert("Please Select For.");
			$("#diagnostic_for").focus();
			return false;
		}

		comments  = $("#comments").val();
		diagnostic_name   = $("#diagnostic_main").val();
		diagnostic_type   = $("#diagnostic_second").val();
		diagnostic_for       = $("#diagnostic_for").val();
		fullPath       = $("#image").val();
		if (fullPath) {
    var startIndex = (fullPath.indexOf('\\') >= 0 ? fullPath.lastIndexOf('\\') : fullPath.lastIndexOf('/'));
    var image = fullPath.substring(startIndex);
    if (image.indexOf('\\') === 0 || image.indexOf('/') === 0) {
        image = image.substring(1);
    }
    //alert(image);
		}
		created_date     = $("#created_date").val();
		updated_date     = $("#updated_date").val();
		$.ajax({
       method: "POST",
          url: "<?php echo Url::to(['vetd/savecomment']); ?>",
         data: { container_id: "<?php echo $session->get('cid'); ?>", diagnostic_name: diagnostic_name, diagnostic_type:diagnostic_type, comments: comments,image:image, diagnostic_for:diagnostic_for, created_date:created_date, updated_date:updated_date, created_by:"<?php echo $session->get('employee_name'); ?>"}
        })
       .done(function( msg ) {
		   alert("נשמר בהצלחה!");
         setTimeout(function() {
        $("#vetd").trigger('click');
    },1);
       });
	}
</script>

views/vetd/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use app\models\Vetd;

/* @var $this yii\web\View */
/* @var $searchModel app\models\VetSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Vetd');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="row">
	<div class="col-sm-12">
		<div class="btn-group pull-right m-t-15">
		<a class="btn topbtn" href="#tab=w1-tab0" onclick="return addcommentd();">הוספת אבחון</a>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-12">

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        //'filterModel' => $searchModel,
        'columns' => [
            //['class' => 'yii\grid\SerialColumn'],
			[
			'label' => 'תאריך',
			'format' => 'raw',
		   'value' => function($model){
			   $newdate = date('d-m-Y', strtotime($model->date_created));
                return $newdate;
            },
           ],
		   [
			'label' => 'אבחנה ראשית',
			'format' => 'raw',
		   'value' => function($model){
			   return $webteamsdropdowns = Vetd::getDiagonoName($model->diagnostic_name);
            },
           ],
		   [
			'label' => 'אבחנה משנית',
			'format' => 'raw',
		   'value' => function($model){
			   return $webteamsdropdowns = Vetd::getDiagonoName($model->diagnostic_type);
            },
           ],
		   [
			'label' => 'הערה',
			'format' => 'raw',
		   'value' => function($model){
			   return $model->comments;
            },
           ],

			[
			'label' => 'עבור',
			'format' => 'raw',
		   'value' => function($model){
                return Vetd::getFish($model->diagnostic_for);
            },
           ],
           // ['class' => 'yii\grid\ActionColumn'],
		   ['class' => 'yii\grid\ActionColumn',
			 	'buttons' => [

			'update' => function ($url, $model, $key) {
				   return '<a href="JavaScript:void(0);" onclick="vetdupdate('.$model->vedt_id.');" ><span class="glyphicon glyphicon-pencil"></span></a>';
                },

			'delete' => function ($url, $model, $key)
				{
					return '<a href="JavaScript:void(0);" onclick="vetddelete('.$model->vedt_id.');" ><span class="glyphicon glyphicon-trash"></span></a>';

                },

            ],
            'template' => '{update} {delete}'


        ],
        ],

    ]); ?>
    </div>
</div>

views/vetd/update.php
<?php

use yii\helpers\Html;
use  yii\web\Session;
use yii\helpers\Url;
use app\models\Diagnostic;

$session = Yii::$app->session;

/* @var $this yii\web\View */
/* @var $model app\models\Vet */

$this->title = Yii::t('app', 'Update Vet: ' . $model->vedt_id, [
    'nameAttribute' => '' . $model->vedt_id,
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Vets'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->vedt_id, 'url' => ['view', 'id' => $model->vedt_id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');

$post = Yii::$app->request->post();
$data = $model->getFishDataDrop($post['cid']);
$diagnoModel  = new Diagnostic();
$parentDrop = $diagnoModel->getParentData();
$secondDrop = $diagnoModel->getSecondDropdown($model->diagnostic_name);
?>
<div class="row">
	<div class="col-sm-12">
	     <h1>עדכון אבחון</h1>
		<div class="btn-group pull-right m-t-15">
         <a class="btn topbtn" href="#tab=w0-tab2" onclick="return backfood();">חזור</a>
        </div>
    </div>
</div>

<div class="row">
<div class="col-sm-12">
<div class="col-sm-4"></div>
<div class="col-sm-4">
<form id="w0" action="" method="post">


     <div class="form-group field-fish-s_name required">
		<label class="control-label" for="fish-s_name">אבחנה ראשית</label>
		<select class="form-control" id="diagnostic_main" name="diagnostic_main" style="height: 36px;" onchange="setseconddropdown(this.value);">
        <option value="0">Select Main Diagnostic</option>
		  <?php foreach($parentDrop as $parentDrops){ ?>
			<option value="<?php echo $parentDrops['d_id']; ?>"  <?=$model->diagnostic_name == $parentDrops['d_id'] ? ' selected="selected"' : '';?>><?php echo $parentDrops['d_name']; ?></option>
		  <?php } ?>

		  </select>

    </div>

    <div class="form-group field-fish-s_name required">
		<label class="control-label" for="fish-s_name">אבחנה משנית</label>
		<select class="form-control" id="diagnostic_second" name="diagnostic_second" style="height: 36px;">
			 <option value="0">Select Main Diagnostic</option>
		  <?php foreach($secondDrop as $secondDrops){ ?>
			<option value="<?php echo $secondDrops['d_id']; ?>"  <?=$model->diagnostic_type == $secondDrops['d_id'] ? ' selected="selected"' : '';?>><?php echo $secondDrops['d_name']; ?></option>
		  <?php } ?>
		  </select>

    </div>

    <div class="form-group field-fish-s_name required">
		<label class="control-label" for="fish-s_name">עבור</label>
		<select class="form-control" id="diagnostic_for" name="diagnostic_for" style="height: 36px;">
		  <?php foreach($data as $fishDrop){ ?>
			<option value="<?php echo $fishDrop['fid']; ?>"  <?=$model->diagnostic_for == $fishDrop['fid'] ? ' selected="selected"' : '';?>><?php echo $fishDrop['name']; ?></option>
		  <?php } ?>
			<option value="0" <?=$model->diagnostic_for == 0 ? ' selected="selected"' : '';?>>All Container</option>
		  </select>
    </div>


    <div class="form-group field-fish-name required">
		<label class="control-label" for="fish-name">הערה</label>
		<textarea cols="5" rows="3" name="comments" class="form-control" id="comments"><?php echo $model->comments; ?></textarea>
		<div class="help-block"></div>
	</div>



    <div class="form-group field-fish-created_date required">
	<input id="vet_id" class="form-control" name="vet_id" value="<?php echo $model->vedt_id; ?>" type="hidden">
		<input id="created_date" class="form-control" name="created_date" value="<?php echo $model->date_created; ?>" type="hidden">
		<input id="updated_date" class="form-control" name="updated_date" value="<?php echo date ("Y-m-d H:i:s"); ?>" type="hidden">
	</div>

    <div class="form-group "><button type="button" class="btn topbtn fa fa-floppy-o" onclick="return updatevetd();"> שמור </button></div>

    </form>
</div>
<div class="col-sm-4"></div>

</div>
</div>
</div>
<script>
	function backfood(){
        $("#vetd").trigger('click');
	}

</script>

views/vetd/upload.php
<?php

if(isset($_POST['btn_upload')){

$filetmp = $FILES["file_img"]["tmp_name"];
$filename = $FILES["file_img"]["name"];
$filetype = $FILES["file_img"]["name"];
$filepath = "uploads/".$filename;

move_uploaded_file($filetmp, $filepath);
}

?>

views/vetd/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Vet */

$this->title = $model->vedt_id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Vets'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="vet-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->vedt_id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->vedt_id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'vet_id',
            'container_id',
            'diagnostic_for',
            'comments:ntext',
            'date_created',
        ],
    ]) ?>

</div>